using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MAZ_Gestion_Arche
{
    public partial class Form1 : DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm
    {
        private DataSet XmlProjectSource = new DataSet("XMLProjectSource");
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Create a new DataSet
            //System.Data.DataSet xmlDataSet = new System.Data.DataSet("XML DataSet");
            // Load the XML document to the DataSet
            XmlProjectSource.ReadXml(@"C:\Projet Visual Studio\MAZ_Gestion_Arche\MAZ_Gestion_Arche\BDD\Project.xml");
            // This line of code is generated by Data Source Configuration Wizard
            GC_ProjectToBuild.DataSource = XmlProjectSource.Tables["PROJECT"];
            
        }

        private void GC_ProjectToBuild_DoubleClick(object sender, EventArgs e)
        {
            lbl_TitreProject.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["NAME"].ToString();
            Lbl_DescriptionDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["DESCRIPTION"].ToString();
            lbl_CultureDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["CULTURE"].ToString();
            lbl_TechnologieDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["TECHNOLOGIE"].ToString();
            lbl_DefenseDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["DEFENSE"].ToString();
            lbl_NourritureDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["NOURRITURE"].ToString();
            lbl_SkillDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["SKILL"].ToString();
            lbl_OtherDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["OTHER"].ToString();
            lbl_TempsTravailDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["WORK"].ToString();
            lbl_SpecialDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["SPECIAL"].ToString();
            lbl_BonusDetail.Text += XmlProjectSource.Tables["PROJECT"].Rows[((DevExpress.XtraGrid.Views.Base.ColumnView)((DevExpress.XtraGrid.GridControl)sender).FocusedView).FocusedRowHandle]["BONUS"].ToString();
            FP_DetailCard.ShowPopup();
        }

        private void FP_DetailCard_ButtonClick(object sender, DevExpress.Utils.FlyoutPanelButtonClickEventArgs e)
        {
            FP_DetailCard.HidePopup();
        }

    }
}
